In [3]:
import numpy as np

In [4]:
list1=[1,2,3,4,5,6]

In [5]:
list1

[1, 2, 3, 4, 5, 6]

In [6]:
arr=np.array(list1)

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
list1+2

TypeError: can only concatenate list (not "int") to list

In [9]:
arr+2

array([3, 4, 5, 6, 7, 8])

In [10]:
list2=[[1,1,1],[2,2,2],[3,3,3]]
arr2=np.array(list2)
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [11]:
type(arr2)

numpy.ndarray

In [12]:
arr2.dtype

dtype('int32')

In [13]:
arr2=np.array(list2,dtype='float')
arr2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [14]:
arr2.astype('int')

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [15]:
arr2.astype('str')

array([['1.0', '1.0', '1.0'],
       ['2.0', '2.0', '2.0'],
       ['3.0', '3.0', '3.0']], dtype='<U32')

In [16]:
np2list=arr2.tolist()
np2list

[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [17]:
arr2.tostring()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

In [18]:
arr2.tobytes()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

# dtype and shape

In [19]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [20]:
arr2.astype(float)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [21]:
print('Shape:',arr2.shape)

Shape: (3, 3)


In [22]:
arr2.size

9

In [23]:
arr.size

6

In [24]:
arr2.dtype

dtype('float64')

In [25]:
arr.ndim

1

In [26]:
arr2.ndim

2

extracting an element from array

In [27]:
arr2[0]

array([1., 1., 1.])

In [28]:
arr2[2][2]

3.0

In [29]:
arr[3]

4

In [30]:
boolarr=arr2<2

In [31]:
boolarr


array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [32]:
list3=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(list3)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar[::-1, ]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [35]:
ar[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# np.nan and np.inf

In [36]:
np.nan

nan

In [37]:
np.inf

inf

In [38]:
arr2[0][0]=np.nan
arr2[0][1]=np.inf
arr2

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [39]:
np.isnan(arr2)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [40]:
np.isinf(arr2)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [41]:
missing_val=np.isnan(arr2) | np.isinf(arr2)
missing_val

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [42]:
arr2[missing_val]=0

In [43]:
arr2

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# statistical operations 

In [44]:
arr2.mean()

1.7777777777777777

In [45]:
arr2.max()

3.0

In [46]:
arr2.min()

0.0

In [47]:
arr2.std()

1.1331154474650633

In [48]:
arr2.var()

1.2839506172839505

In [49]:
arr2.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [50]:
a=arr2[:2,:2]

In [51]:
arr2

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [52]:
a

array([[0., 0.],
       [2., 2.]])

In [53]:
arr2.reshape(9,1)

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [54]:
arr2.flatten()

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

# sequence , repetition and random numbers

In [55]:
np.arange(1,5,dtype='float')

array([1., 2., 3., 4.])

In [56]:
np.linspace(1,15,9)

array([ 1.  ,  2.75,  4.5 ,  6.25,  8.  ,  9.75, 11.5 , 13.25, 15.  ])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.ones(2)

array([1., 1.])

In [59]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [60]:
np.repeat(arr2, repeats = 3)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [61]:
np.repeat(arr2, repeats = 3, axis = 1)

array([[0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [62]:
np.repeat(arr2, repeats = 3, axis = 0)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [63]:
np.random.rand(3,3)

array([[0.02683963, 0.45716257, 0.34898383],
       [0.4425585 , 0.70698771, 0.75765188],
       [0.50604455, 0.0913549 , 0.82014697]])

In [64]:

np.random.randn(3,3)

array([[ 1.15535202,  1.154525  , -0.88005766],
       [-1.64572169,  0.32271451,  3.34451918],
       [ 0.55736835, -1.84888023, -0.05056205]])

In [65]:
np.random.randint(3,789)

574

In [66]:
np.random.seed(0)

In [67]:
np.unique(arr2)

array([0., 1., 2., 3.])

In [68]:
uniques, counts = np.unique(arr2,return_counts = True)

In [69]:
uniques

array([0., 1., 2., 3.])

In [70]:
 counts

array([2, 1, 3, 3], dtype=int64)

# numpy part 2

In [77]:
arr=np.array([14,2,34,68,4,7,9,23])
arr

array([14,  2, 34, 68,  4,  7,  9, 23])

In [78]:
index_gt15=np.where(arr<15)
index_gt15

(array([0, 1, 4, 5, 6], dtype=int64),)

In [79]:
arr[index_gt15]

array([14,  2,  4,  7,  9])

In [80]:
arr[arr<15]

array([14,  2,  4,  7,  9])

In [81]:
arr<15

array([ True,  True, False, False,  True,  True,  True, False])

In [82]:
np.where(arr<15,'lt15','gt15')

array(['lt15', 'lt15', 'gt15', 'gt15', 'lt15', 'lt15', 'lt15', 'gt15'],
      dtype='<U4')

In [83]:
arr

array([14,  2, 34, 68,  4,  7,  9, 23])

In [84]:
arr.max()

68

In [85]:
arr.argmax()

3

In [86]:
arr[arr.argmax()]

68

In [87]:
arr.min()

2

In [88]:
arr.argmin()

1

In [89]:
arr[arr.argmin()]

2

In [91]:
dt2 = np.genfromtxt('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv',delimiter = ',',
                      skip_header = 1,filling_values = -1000, dtype = 'float')

In [92]:

np.set_printoptions(suppress = True)
dt2

array([[    5.1,     3.5,     1.4,     0.2, -1000. ],
       [    4.9,     3. ,     1.4,     0.2, -1000. ],
       [    4.7,     3.2,     1.3,     0.2, -1000. ],
       [    4.6,     3.1,     1.5,     0.2, -1000. ],
       [    5. ,     3.6,     1.4,     0.2, -1000. ],
       [    5.4,     3.9,     1.7,     0.4, -1000. ],
       [    4.6,     3.4,     1.4,     0.3, -1000. ],
       [    5. ,     3.4,     1.5,     0.2, -1000. ],
       [    4.4,     2.9,     1.4,     0.2, -1000. ],
       [    4.9,     3.1,     1.5,     0.1, -1000. ],
       [    5.4,     3.7,     1.5,     0.2, -1000. ],
       [    4.8,     3.4,     1.6,     0.2, -1000. ],
       [    4.8,     3. ,     1.4,     0.1, -1000. ],
       [    4.3,     3. ,     1.1,     0.1, -1000. ],
       [    5.8,     4. ,     1.2,     0.2, -1000. ],
       [    5.7,     4.4,     1.5,     0.4, -1000. ],
       [    5.4,     3.9,     1.3,     0.4, -1000. ],
       [    5.1,     3.5,     1.4,     0.3, -1000. ],
       [    5.7,     3.8,   

In [93]:
dt2.shape

(150, 5)

In [94]:
dt2[:3]

array([[    5.1,     3.5,     1.4,     0.2, -1000. ],
       [    4.9,     3. ,     1.4,     0.2, -1000. ],
       [    4.7,     3.2,     1.3,     0.2, -1000. ]])

 ## concat row and column wise 

In [96]:
arrA=np.ones((4,4))
arrB=np.zeros((4,4))

In [97]:
arrA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
arrB

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
#np.concatenate() , np.vstack(), np.r_

In [100]:
np.concatenate([arrA,arrB],axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.vstack([arrA,arrB])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
np.r_[arrA,arrB]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
np.concatenate([arrA,arrB],axis=1)

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [106]:
np.hstack([arrA,arrB])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [107]:
np.c_[arrA,arrB]

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

## sort a numpy array

In [112]:
arr=np.random.randint(1,10,size=[4,3])
arr

array([[9, 2, 7],
       [8, 8, 9],
       [2, 6, 9],
       [5, 4, 1]])

In [113]:
np.sort(arr,axis=0)

array([[2, 2, 1],
       [5, 4, 7],
       [8, 6, 9],
       [9, 8, 9]])

In [114]:
np.sort(arr,axis=1)

array([[2, 7, 9],
       [8, 8, 9],
       [2, 6, 9],
       [1, 4, 5]])

In [117]:
arr[:,2].argsort()

array([3, 0, 1, 2], dtype=int64)

## working with  data

In [121]:
d=np.datetime64('2020-07-28 23:56:00')
d

numpy.datetime64('2020-07-28T23:56:00')

In [122]:
oneday=np.timedelta64(1,'D')

In [123]:
oneday

numpy.timedelta64(1,'D')

In [124]:
d + oneday

numpy.datetime64('2020-07-29T23:56:00')

In [125]:
oneminute=oneday=np.timedelta64(1,'m')

In [126]:
d+oneminute

numpy.datetime64('2020-07-28T23:57:00')

In [127]:
onehour=np.timedelta64(1,'h')

In [128]:
d+onehour

numpy.datetime64('2020-07-29T00:56:00')

In [129]:
dates=np.arange(np.datetime64('2019-06-02'),np.datetime64('2020-06-02'))

In [130]:
dates

array(['2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05',
       '2019-06-06', '2019-06-07', '2019-06-08', '2019-06-09',
       '2019-06-10', '2019-06-11', '2019-06-12', '2019-06-13',
       '2019-06-14', '2019-06-15', '2019-06-16', '2019-06-17',
       '2019-06-18', '2019-06-19', '2019-06-20', '2019-06-21',
       '2019-06-22', '2019-06-23', '2019-06-24', '2019-06-25',
       '2019-06-26', '2019-06-27', '2019-06-28', '2019-06-29',
       '2019-06-30', '2019-07-01', '2019-07-02', '2019-07-03',
       '2019-07-04', '2019-07-05', '2019-07-06', '2019-07-07',
       '2019-07-08', '2019-07-09', '2019-07-10', '2019-07-11',
       '2019-07-12', '2019-07-13', '2019-07-14', '2019-07-15',
       '2019-07-16', '2019-07-17', '2019-07-18', '2019-07-19',
       '2019-07-20', '2019-07-21', '2019-07-22', '2019-07-23',
       '2019-07-24', '2019-07-25', '2019-07-26', '2019-07-27',
       '2019-07-28', '2019-07-29', '2019-07-30', '2019-07-31',
       '2019-08-01', '2019-08-02', '2019-08-03', '2019-

In [131]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2
    
foo(20)

10.0

In [132]:
foo(11)

121

In [133]:
foo_v = np.vectorize(foo, otypes = [float])

In [134]:
foo_v(arr)

array([[81.,  1., 49.],
       [ 4.,  4., 81.],
       [ 1.,  3., 81.],
       [25.,  2.,  1.]])